In [2]:
import pandas as pd 

df = pd.read_csv('pokemon_data.csv')

# Reading the data

In [10]:
#print(df[['Name', 'HP']][0:11])

#print(df.iloc[2,1])

# df.loc[df['Type 1'] == "Fire"]

df.sort_values(['Type 1', 'HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making changes to the data

In [4]:
#df ['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

#df = df.drop(columns=['Total'])

#df['Total'] = df.iloc[:, 4:10].sum(axis=1)

#cols = list(df.columns.values)
#df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

#df.head(10)

# Saving the data

In [5]:
#df.to_csv('modified.csv', index=False)

#df.to_excel('modified.xlsx', index=False)

#df.to_csv('modified.txt', index=False, sep='\t')

# Filtering data

In [6]:
#grass_poison_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

#grass_poison_df.to_excel('grass_poison.xlsx', index=False)

#Resetting the index
#grass_poison_df.reset_index(drop=True, implace=True)

#Filtering by diiferent names
#df.loc[df['Name'].str.contains('Mega')]
#df.loc[~df['Name'].str.contains('Mega')]

#import re
#df.loc[df['Type 1'].str.contains('Fire', regex=True)]

#Filter by letters in name
#import re
#df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

# Conditional changes

In [7]:
#df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

# Aggregate Statistics

In [8]:
#df = pd.read_csv('pokemon_data.csv')

#df.groupby(['Type 1']).mean().sort_values('Speed', ascending=False)

#Counting
#df['Count'] = 1
#df.groupby(['Type 1']).count()['Count']

# Working with large amounts of data

In [9]:
#new_df = pd.DataFrame(columns=df.columns)

#for df in pd.read_csv('pokemon_data.csv', chunksize=5):
    #results df.groupby((['Type 1'])).count()
    
    #new_df = pd.concat([new_df, results])